DROP DATABASE IF EXISTS hr_db;
CREATE DATABASE hr_db;

USE hr_db;

SELECT DATABASE();

CREATE TABLE department (
    id INT NOT NULL PRIMARY KEY,
    name VARCHAR(30) NOT NULL
);

CREATE TABLE role (
    id INT NOT NULL PRIMARY KEY,
    title VARCHAR(30) NOT NULL,
    department_id INT NULL FOREIGN KEY REFERENCES department(id) ON DELETE SET NULL,
    salary DECIMAL NOT NULL
);

CREATE TABLE employee (
    id INT NOT NULL PRIMARY KEY,
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULL,
    role_id INT NULL FOREIGN KEY REFERENCES role(id) ON DELETE SET NULL,
    manager_id INT NULL FOREIGN KEY REFERENCES employee(id) ON DELETE SET NULL
);